- name: Playbook to provision the QA Environment 
  hosts: all
#  connection: local
  become: no
  gather_facts: true
  roles:
   - osp-setup   #ROle to provision QA Network and Security groups 
   - osp-servers #Role to provision the QA instances
