#- name: Playbook Role to provision 3tier APP  
#  hosts: workstation
#  gather_facts: true
#  roles:
#  - name: osp-facts #Role to provision  3tier APP and  used by the job templates

# Setup database tier



- name: Gather facts to get internal IPs of the servers
  hosts: tag_AnsibleGroup_apps  
  gather_facts: true
  tasks:
    - debug:
        msg: "Internal_IP: {{ hostvars[item]['ansible_default_ipv4'].address }}"
      loop: "{{ groups.tag_AnsibleGroup_apps }}"

- name: setup database tier for prod env
  become: yes
  gather_facts: true
  hosts: tag_AnsibleGroup_appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier-prod, tags: [dbs_prod, postgres_prod]}


# Setup application servers tier

- name: setup app tier for prod env
  hosts: tag_AnsibleGroup_apps
  become: yes
  gather_facts: false
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier-prod, tags: [apps_prod, tomcat_prod]}



# Setup front-end load balancer tier


#- name: setup load-balancer tier for prod env
#  hosts: frontends
#  become: yes
#  roles:
#    - {name: base-config, tags: base-config}
#    - {name: lb-tier-prod, tags: [lbs_prod, haproxy_prod]}


