- name: Playbook to provision the QA Environment
  hosts: localhost
  connection: local
  become: no
  gather_facts: true
  roles:
   - osp-servers #Role to provision the QA and used by the job template "Provision QA Environment"
