
- name: Create Homework Assignment project
  tower_project:
    name: "Homework_Assignment_Project"
    description: "Homework Assignment Project"
    organization: Default
    state: present
    scm_type: git
    scm_url: "{{ scm_url }}" 
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
#    tower_username: "{{ _tower_user_name }}"
#    tower_password: "{{ _tower_password }}"
    tower_config_file: "~/.tower_cli.cfg"
    tower_verify_ssl: no

- name: Machine Credentail to connect to workstation using openstack.pub
  tower_credential:
    name: Connect_to_workstation
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
#    tower_username: "{{ _tower_user_name }}"
#    tower_password: "{{ _tower_password }}"
    tower_config_file: "~/.tower_cli.cfg"
    ssh_key_data: "/root/.ssh/openstack.pem"
    username: cloud-user

- name: Create Inventory
  command: |
    tower-cli inventory create -n "{{static_inventory_name}}" --organization "{{org_name}}"

- name: Create Group in static inventory 
  command: |
    tower-cli group create --inventory "{{static_inventory_name}}"  --name "{{group_name}}"


- name: Add tower host
  tower_host:
    name: "{{host_name}}"
    description: "workstation"
    inventory: "{{static_inventory_name}}"
    state: present
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
#    tower_username: "{{ _tower_user_name }}"
#    tower_password: "{{ _tower_password }}"
    tower_config_file: "~/.tower_cli.cfg"
    tower_verify_ssl: no

- name: Associate workstation host to group 
  command: | 
    tower-cli host associate --host "{{host_name}}" --group "{{group_name}}"


- name: Tower Creds key file
  tower_credential:
    name: "{{ opentlc_cred_name }}"
    organization: Default
    state: present
    kind: ssh
    tower_host: tower1.{{tower_GUID}}.example.opentlc.com
#    tower_username: "{{ _tower_user_name }}"
#    tower_password: "{{ _tower_password }}"
    tower_config_file: "~/.tower_cli.cfg"
    tower_verify_ssl: no
    ssh_key_data: /root/.ssh/openstack.pem
    username: "{{ opentlc_login }}"

- name: Remove secret
  file:
    name: /root/secret.pem
    state: absent

