---
# Initial, common, system setup steps

#- name: enable sudo without tty for some ansible commands
#  replace:
#    path: /etc/sudoers
#    regexp: '^Defaults\s*requiretty'
#    replace: 'Defaults  !requiretty'
#    backup: yes

- name: Get internal repo file
  get_url:
    url: "{{ internal_repo_path  }}"
    dest: "{{ role_path }}/files/internal.repo"
    mode: 0755
  delegate_to: localhost

- name: Copy internal repo file
  copy: 
    src: "{{ role_path }}/files/internal.repo"
    dest: /etc/yum.repos.d/internal.repo
    owner: root
    group: root
    mode: 0755  

 
#- name: install base tools and packages

